### ISSUE TITLE
The module @rebilly/swagger-combine does not work in node.js

### ISSUE THREAD

**Issue by heylar** [Rebilly/swagger-combine#2]
Hi Roman,

I am using your module @rebilly/swagger-combine to combine multiple swagger files into a single file. I would like to use this functionality within a node.js script. The CLI tool is working, however when I attempt to follow and run the example code within a script, the module does not work at all for me.

E.g. In a file script1.js:
```
const { combineSpecs } = require('@rebilly/swagger-combine');

const merged = combineSpecs([
  'swagger1.json',
  'swagger2.json',
  'swagger3.json',
]);
```

When I run the command ``node script1.js``, the help dialogue appears. When I run the command ``node script1.js out1.js input1.js`` I receive the following error message:
```
TypeError: combineSpecs is not a function
    at Object.<anonymous> (C:\Users\l100221\Downloads\BUILD\WDP-4405-merge-swagger-for-swimlanes\rebilly-swagger-combine\swagger_combiner\script2.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)
```
How can I run this tool inside a node.js script to combine multiple swagger files? Thanks for your help.

**Comment by athiththan11** [comment]
Hi,
I am also facing the same issue. 
Is that a known issue in the latest versions? How we can overcome this?
Thanks in advance.
